alb:
  addr: 0.0.0.0
  ports:
    http: 3000
  reconciliation: /reconcile

secrets:
  private_key:
    location: s3
    bucket: configuration-68f6c7
    key: f2/private.key

services:
  nginx:
    image: nginx
    tag: latest
    replicas: 1
    routes:
      - host: localhost:3000
        port: 80
    proxy_settings:
      preserve_client_version: true
    shutdown_mode: graceful
    volumes:
      config:
        source:
          location: filesystem
          path: /Users/personal/Documents/code/f2/development/nginx.conf
        target: /etc/nginx/nginx.conf
