events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
		http2 on;
        
        location / {
            return 200 "$server_protocol response from nginx\n";
            add_header Content-Type text/plain;
        }
    }
}
