[package]
name = "f2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.56.0"
aws-sdk-s3 = "0.29.0"
base64 = "0.21.2"
chrono = "0.4.24"
color-eyre = "0.6.2"
futures = "0.3.28"
hyper = { version = "0.14.25", features = ["client", "server", "tcp", "http1"] }
hyper-rustls = "0.24.1"
hyperlocal = "0.8.0"
pico-args = "0.5.0"
rand = { version = "0.8.5", features = ["small_rng"] }
rsa = "0.9.2"
rustls = "0.21.6"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_yaml = "0.9.21"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "time", "fs"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dev-dependencies]
hex = "0.4.3"
