[package]
name = "f2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
docker-api = "0.9.1"
hyper = { version = "0.14.20", features = ["client", "server", "tcp", "http1"] }
rand = "0.8.5"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "fmt"], default-features = false }
