[package]
name = "f2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
dkregistry = { git = "https://github.com/camallo/dkregistry-rs", rev = "37acecb", features = ["reqwest-rustls"] }
futures = "0.3.28"
hyper = { version = "0.14.25", features = ["client", "server", "tcp", "http1"] }
hyperlocal = "0.8.0"
pico-args = "0.5.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_yaml = "0.9.21"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
